NewMap1_MapScripts::
	.byte 0


negro_sombra1::
# 5 "data/maps/NewMap1/scripts.pory"
	lock
# 6 "data/maps/NewMap1/scripts.pory"
	msgbox negro_sombra1_Text_0
# 7 "data/maps/NewMap1/scripts.pory"
	release
	return


negro_sombra1_Text_0:
# 6 "data/maps/NewMap1/scripts.pory"
	.string "¿Que haces aca?\n"
	.string "No deberias estar aqui...\p"
	.string "Bueno, no importa.\p"
	.string "Me presento, soy ???\p"
	.string "Cuentame sobre ti$"
